# Generated by Django 4.2.16 on 2024-09-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
