# Generated by Django 4.2.16 on 2025-01-31 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.time(14, 0), editable=False),
        ),
    ]
