# Generated by Django 4.2.16 on 2025-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
